import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const COUNTRIES: Array<{
  name: string; nameAr: string; iso2: string; iso3: string; dialCode: string;
  currencyCode: string; currencyName: string; currencySymbol: string;
  defaultLanguage: string; region: string; timezone: string;
}> = [
  { name: 'Egypt', nameAr: 'مصر', iso2: 'EG', iso3: 'EGY', dialCode: '+20', currencyCode: 'EGP', currencyName: 'Egyptian Pound', currencySymbol: 'E£', defaultLanguage: 'ar', region: 'Africa', timezone: 'Africa/Cairo' },
  { name: 'Saudi Arabia', nameAr: 'السعودية', iso2: 'SA', iso3: 'SAU', dialCode: '+966', currencyCode: 'SAR', currencyName: 'Saudi Riyal', currencySymbol: 'SR', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Riyadh' },
  { name: 'United Arab Emirates', nameAr: 'الإمارات', iso2: 'AE', iso3: 'ARE', dialCode: '+971', currencyCode: 'AED', currencyName: 'UAE Dirham', currencySymbol: 'AED', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Dubai' },
  { name: 'Kuwait', nameAr: 'الكويت', iso2: 'KW', iso3: 'KWT', dialCode: '+965', currencyCode: 'KWD', currencyName: 'Kuwaiti Dinar', currencySymbol: 'KD', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Kuwait' },
  { name: 'Qatar', nameAr: 'قطر', iso2: 'QA', iso3: 'QAT', dialCode: '+974', currencyCode: 'QAR', currencyName: 'Qatari Riyal', currencySymbol: 'QR', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Qatar' },
  { name: 'Bahrain', nameAr: 'البحرين', iso2: 'BH', iso3: 'BHR', dialCode: '+973', currencyCode: 'BHD', currencyName: 'Bahraini Dinar', currencySymbol: 'BD', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Bahrain' },
  { name: 'Oman', nameAr: 'عمان', iso2: 'OM', iso3: 'OMN', dialCode: '+968', currencyCode: 'OMR', currencyName: 'Omani Rial', currencySymbol: 'ر.ع', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Muscat' },
  { name: 'Jordan', nameAr: 'الأردن', iso2: 'JO', iso3: 'JOR', dialCode: '+962', currencyCode: 'JOD', currencyName: 'Jordanian Dinar', currencySymbol: 'JD', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Amman' },
  { name: 'Iraq', nameAr: 'العراق', iso2: 'IQ', iso3: 'IRQ', dialCode: '+964', currencyCode: 'IQD', currencyName: 'Iraqi Dinar', currencySymbol: 'ع.د', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Baghdad' },
  { name: 'Lebanon', nameAr: 'لبنان', iso2: 'LB', iso3: 'LBN', dialCode: '+961', currencyCode: 'LBP', currencyName: 'Lebanese Pound', currencySymbol: 'ل.ل', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Beirut' },
  { name: 'Syria', nameAr: 'سوريا', iso2: 'SY', iso3: 'SYR', dialCode: '+963', currencyCode: 'SYP', currencyName: 'Syrian Pound', currencySymbol: '£', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Damascus' },
  { name: 'Palestine', nameAr: 'فلسطين', iso2: 'PS', iso3: 'PSE', dialCode: '+970', currencyCode: 'ILS', currencyName: 'Israeli Shekel', currencySymbol: '₪', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Gaza' },
  { name: 'Yemen', nameAr: 'اليمن', iso2: 'YE', iso3: 'YEM', dialCode: '+967', currencyCode: 'YER', currencyName: 'Yemeni Rial', currencySymbol: '﷼', defaultLanguage: 'ar', region: 'Asia', timezone: 'Asia/Aden' },
  { name: 'Sudan', nameAr: 'السودان', iso2: 'SD', iso3: 'SDN', dialCode: '+249', currencyCode: 'SDG', currencyName: 'Sudanese Pound', currencySymbol: '£', defaultLanguage: 'ar', region: 'Africa', timezone: 'Africa/Khartoum' },
  { name: 'Libya', nameAr: 'ليبيا', iso2: 'LY', iso3: 'LBY', dialCode: '+218', currencyCode: 'LYD', currencyName: 'Libyan Dinar', currencySymbol: 'LD', defaultLanguage: 'ar', region: 'Africa', timezone: 'Africa/Tripoli' },
  { name: 'Tunisia', nameAr: 'تونس', iso2: 'TN', iso3: 'TUN', dialCode: '+216', currencyCode: 'TND', currencyName: 'Tunisian Dinar', currencySymbol: 'DT', defaultLanguage: 'ar', region: 'Africa', timezone: 'Africa/Tunis' },
  { name: 'Algeria', nameAr: 'الجزائر', iso2: 'DZ', iso3: 'DZA', dialCode: '+213', currencyCode: 'DZD', currencyName: 'Algerian Dinar', currencySymbol: 'DA', defaultLanguage: 'ar', region: 'Africa', timezone: 'Africa/Algiers' },
  { name: 'Morocco', nameAr: 'المغرب', iso2: 'MA', iso3: 'MAR', dialCode: '+212', currencyCode: 'MAD', currencyName: 'Moroccan Dirham', currencySymbol: 'DH', defaultLanguage: 'ar', region: 'Africa', timezone: 'Africa/Casablanca' },
  { name: 'Mauritania', nameAr: 'موريتانيا', iso2: 'MR', iso3: 'MRT', dialCode: '+222', currencyCode: 'MRU', currencyName: 'Mauritanian Ouguiya', currencySymbol: 'UM', defaultLanguage: 'ar', region: 'Africa', timezone: 'Africa/Nouakchott' },
  { name: 'Djibouti', nameAr: 'جيبوتي', iso2: 'DJ', iso3: 'DJI', dialCode: '+253', currencyCode: 'DJF', currencyName: 'Djiboutian Franc', currencySymbol: 'Fdj', defaultLanguage: 'ar', region: 'Africa', timezone: 'Africa/Djibouti' },
  { name: 'Comoros', nameAr: 'جزر القمر', iso2: 'KM', iso3: 'COM', dialCode: '+269', currencyCode: 'KMF', currencyName: 'Comorian Franc', currencySymbol: 'CF', defaultLanguage: 'ar', region: 'Africa', timezone: 'Indian/Comoro' },
  { name: 'Somalia', nameAr: 'الصومال', iso2: 'SO', iso3: 'SOM', dialCode: '+252', currencyCode: 'SOS', currencyName: 'Somali Shilling', currencySymbol: 'Sh', defaultLanguage: 'so', region: 'Africa', timezone: 'Africa/Mogadishu' },
  { name: 'South Sudan', nameAr: 'جنوب السودان', iso2: 'SS', iso3: 'SSD', dialCode: '+211', currencyCode: 'SSP', currencyName: 'South Sudanese Pound', currencySymbol: '£', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Juba' },
  { name: 'United States', nameAr: 'الولايات المتحدة', iso2: 'US', iso3: 'USA', dialCode: '+1', currencyCode: 'USD', currencyName: 'US Dollar', currencySymbol: '$', defaultLanguage: 'en', region: 'Americas', timezone: 'America/New_York' },
  { name: 'United Kingdom', nameAr: 'المملكة المتحدة', iso2: 'GB', iso3: 'GBR', dialCode: '+44', currencyCode: 'GBP', currencyName: 'British Pound', currencySymbol: '£', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/London' },
  { name: 'Germany', nameAr: 'ألمانيا', iso2: 'DE', iso3: 'DEU', dialCode: '+49', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'de', region: 'Europe', timezone: 'Europe/Berlin' },
  { name: 'France', nameAr: 'فرنسا', iso2: 'FR', iso3: 'FRA', dialCode: '+33', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'fr', region: 'Europe', timezone: 'Europe/Paris' },
  { name: 'Italy', nameAr: 'إيطاليا', iso2: 'IT', iso3: 'ITA', dialCode: '+39', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'it', region: 'Europe', timezone: 'Europe/Rome' },
  { name: 'Spain', nameAr: 'إسبانيا', iso2: 'ES', iso3: 'ESP', dialCode: '+34', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'es', region: 'Europe', timezone: 'Europe/Madrid' },
  { name: 'Portugal', nameAr: 'البرتغال', iso2: 'PT', iso3: 'PRT', dialCode: '+351', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'pt', region: 'Europe', timezone: 'Europe/Lisbon' },
  { name: 'Netherlands', nameAr: 'هولندا', iso2: 'NL', iso3: 'NLD', dialCode: '+31', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Amsterdam' },
  { name: 'Belgium', nameAr: 'بلجيكا', iso2: 'BE', iso3: 'BEL', dialCode: '+32', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Brussels' },
  { name: 'Switzerland', nameAr: 'سويسرا', iso2: 'CH', iso3: 'CHE', dialCode: '+41', currencyCode: 'CHF', currencyName: 'Swiss Franc', currencySymbol: 'CHF', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Zurich' },
  { name: 'Austria', nameAr: 'النمسا', iso2: 'AT', iso3: 'AUT', dialCode: '+43', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Vienna' },
  { name: 'Sweden', nameAr: 'السويد', iso2: 'SE', iso3: 'SWE', dialCode: '+46', currencyCode: 'SEK', currencyName: 'Swedish Krona', currencySymbol: 'kr', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Stockholm' },
  { name: 'Norway', nameAr: 'النرويج', iso2: 'NO', iso3: 'NOR', dialCode: '+47', currencyCode: 'NOK', currencyName: 'Norwegian Krone', currencySymbol: 'kr', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Oslo' },
  { name: 'Denmark', nameAr: 'الدنمارك', iso2: 'DK', iso3: 'DNK', dialCode: '+45', currencyCode: 'DKK', currencyName: 'Danish Krone', currencySymbol: 'kr', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Copenhagen' },
  { name: 'Finland', nameAr: 'فنلندا', iso2: 'FI', iso3: 'FIN', dialCode: '+358', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Helsinki' },
  { name: 'Ireland', nameAr: 'أيرلندا', iso2: 'IE', iso3: 'IRL', dialCode: '+353', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Dublin' },
  { name: 'Greece', nameAr: 'اليونان', iso2: 'GR', iso3: 'GRC', dialCode: '+30', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Athens' },
  { name: 'Poland', nameAr: 'بولندا', iso2: 'PL', iso3: 'POL', dialCode: '+48', currencyCode: 'PLN', currencyName: 'Polish Zloty', currencySymbol: 'zł', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Warsaw' },
  { name: 'Russia', nameAr: 'روسيا', iso2: 'RU', iso3: 'RUS', dialCode: '+7', currencyCode: 'RUB', currencyName: 'Russian Ruble', currencySymbol: '₽', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Moscow' },
  { name: 'Turkey', nameAr: 'تركيا', iso2: 'TR', iso3: 'TUR', dialCode: '+90', currencyCode: 'TRY', currencyName: 'Turkish Lira', currencySymbol: '₺', defaultLanguage: 'tr', region: 'Asia', timezone: 'Europe/Istanbul' },
  { name: 'Iran', nameAr: 'إيران', iso2: 'IR', iso3: 'IRN', dialCode: '+98', currencyCode: 'IRR', currencyName: 'Iranian Rial', currencySymbol: '﷼', defaultLanguage: 'fa', region: 'Asia', timezone: 'Asia/Tehran' },
  { name: 'India', nameAr: 'الهند', iso2: 'IN', iso3: 'IND', dialCode: '+91', currencyCode: 'INR', currencyName: 'Indian Rupee', currencySymbol: '₹', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Kolkata' },
  { name: 'Pakistan', nameAr: 'باكستان', iso2: 'PK', iso3: 'PAK', dialCode: '+92', currencyCode: 'PKR', currencyName: 'Pakistani Rupee', currencySymbol: 'Rs', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Karachi' },
  { name: 'Bangladesh', nameAr: 'بنغلاديش', iso2: 'BD', iso3: 'BGD', dialCode: '+880', currencyCode: 'BDT', currencyName: 'Bangladeshi Taka', currencySymbol: '৳', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Dhaka' },
  { name: 'Indonesia', nameAr: 'إندونيسيا', iso2: 'ID', iso3: 'IDN', dialCode: '+62', currencyCode: 'IDR', currencyName: 'Indonesian Rupiah', currencySymbol: 'Rp', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Jakarta' },
  { name: 'Malaysia', nameAr: 'ماليزيا', iso2: 'MY', iso3: 'MYS', dialCode: '+60', currencyCode: 'MYR', currencyName: 'Malaysian Ringgit', currencySymbol: 'RM', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Kuala_Lumpur' },
  { name: 'Thailand', nameAr: 'تايلاند', iso2: 'TH', iso3: 'THA', dialCode: '+66', currencyCode: 'THB', currencyName: 'Thai Baht', currencySymbol: '฿', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Bangkok' },
  { name: 'Vietnam', nameAr: 'فيتنام', iso2: 'VN', iso3: 'VNM', dialCode: '+84', currencyCode: 'VND', currencyName: 'Vietnamese Dong', currencySymbol: '₫', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Ho_Chi_Minh' },
  { name: 'Philippines', nameAr: 'الفلبين', iso2: 'PH', iso3: 'PHL', dialCode: '+63', currencyCode: 'PHP', currencyName: 'Philippine Peso', currencySymbol: '₱', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Manila' },
  { name: 'Singapore', nameAr: 'سنغافورة', iso2: 'SG', iso3: 'SGP', dialCode: '+65', currencyCode: 'SGD', currencyName: 'Singapore Dollar', currencySymbol: 'S$', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Singapore' },
  { name: 'China', nameAr: 'الصين', iso2: 'CN', iso3: 'CHN', dialCode: '+86', currencyCode: 'CNY', currencyName: 'Chinese Yuan', currencySymbol: '¥', defaultLanguage: 'zh', region: 'Asia', timezone: 'Asia/Shanghai' },
  { name: 'Japan', nameAr: 'اليابان', iso2: 'JP', iso3: 'JPN', dialCode: '+81', currencyCode: 'JPY', currencyName: 'Japanese Yen', currencySymbol: '¥', defaultLanguage: 'ja', region: 'Asia', timezone: 'Asia/Tokyo' },
  { name: 'South Korea', nameAr: 'كوريا الجنوبية', iso2: 'KR', iso3: 'KOR', dialCode: '+82', currencyCode: 'KRW', currencyName: 'South Korean Won', currencySymbol: '₩', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Seoul' },
  { name: 'Canada', nameAr: 'كندا', iso2: 'CA', iso3: 'CAN', dialCode: '+1', currencyCode: 'CAD', currencyName: 'Canadian Dollar', currencySymbol: 'C$', defaultLanguage: 'en', region: 'Americas', timezone: 'America/Toronto' },
  { name: 'Mexico', nameAr: 'المكسيك', iso2: 'MX', iso3: 'MEX', dialCode: '+52', currencyCode: 'MXN', currencyName: 'Mexican Peso', currencySymbol: 'Mex$', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Mexico_City' },
  { name: 'Brazil', nameAr: 'البرازيل', iso2: 'BR', iso3: 'BRA', dialCode: '+55', currencyCode: 'BRL', currencyName: 'Brazilian Real', currencySymbol: 'R$', defaultLanguage: 'pt', region: 'Americas', timezone: 'America/Sao_Paulo' },
  { name: 'Argentina', nameAr: 'الأرجنتين', iso2: 'AR', iso3: 'ARG', dialCode: '+54', currencyCode: 'ARS', currencyName: 'Argentine Peso', currencySymbol: '$', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Argentina/Buenos_Aires' },
  { name: 'Colombia', nameAr: 'كولومبيا', iso2: 'CO', iso3: 'COL', dialCode: '+57', currencyCode: 'COP', currencyName: 'Colombian Peso', currencySymbol: '$', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Bogota' },
  { name: 'Chile', nameAr: 'تشيلي', iso2: 'CL', iso3: 'CHL', dialCode: '+56', currencyCode: 'CLP', currencyName: 'Chilean Peso', currencySymbol: '$', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Santiago' },
  { name: 'Peru', nameAr: 'بيرو', iso2: 'PE', iso3: 'PER', dialCode: '+51', currencyCode: 'PEN', currencyName: 'Peruvian Sol', currencySymbol: 'S/', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Lima' },
  { name: 'Venezuela', nameAr: 'فنزويلا', iso2: 'VE', iso3: 'VEN', dialCode: '+58', currencyCode: 'VES', currencyName: 'Venezuelan Bolivar', currencySymbol: 'Bs', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Caracas' },
  { name: 'South Africa', nameAr: 'جنوب أفريقيا', iso2: 'ZA', iso3: 'ZAF', dialCode: '+27', currencyCode: 'ZAR', currencyName: 'South African Rand', currencySymbol: 'R', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Johannesburg' },
  { name: 'Nigeria', nameAr: 'نيجيريا', iso2: 'NG', iso3: 'NGA', dialCode: '+234', currencyCode: 'NGN', currencyName: 'Nigerian Naira', currencySymbol: '₦', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Lagos' },
  { name: 'Kenya', nameAr: 'كينيا', iso2: 'KE', iso3: 'KEN', dialCode: '+254', currencyCode: 'KES', currencyName: 'Kenyan Shilling', currencySymbol: 'KSh', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Nairobi' },
  { name: 'Ghana', nameAr: 'غانا', iso2: 'GH', iso3: 'GHA', dialCode: '+233', currencyCode: 'GHS', currencyName: 'Ghanaian Cedi', currencySymbol: '₵', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Accra' },
  { name: 'Ethiopia', nameAr: 'إثيوبيا', iso2: 'ET', iso3: 'ETH', dialCode: '+251', currencyCode: 'ETB', currencyName: 'Ethiopian Birr', currencySymbol: 'Br', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Addis_Ababa' },
  { name: 'Tanzania', nameAr: 'تنزانيا', iso2: 'TZ', iso3: 'TZA', dialCode: '+255', currencyCode: 'TZS', currencyName: 'Tanzanian Shilling', currencySymbol: 'TSh', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Dar_es_Salaam' },
  { name: 'Uganda', nameAr: 'أوغندا', iso2: 'UG', iso3: 'UGA', dialCode: '+256', currencyCode: 'UGX', currencyName: 'Ugandan Shilling', currencySymbol: 'USh', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Kampala' },
  { name: 'Morocco', nameAr: 'المغرب', iso2: 'MA', iso3: 'MAR', dialCode: '+212', currencyCode: 'MAD', currencyName: 'Moroccan Dirham', currencySymbol: 'DH', defaultLanguage: 'ar', region: 'Africa', timezone: 'Africa/Casablanca' },
  { name: 'Australia', nameAr: 'أستراليا', iso2: 'AU', iso3: 'AUS', dialCode: '+61', currencyCode: 'AUD', currencyName: 'Australian Dollar', currencySymbol: 'A$', defaultLanguage: 'en', region: 'Oceania', timezone: 'Australia/Sydney' },
  { name: 'New Zealand', nameAr: 'نيوزيلندا', iso2: 'NZ', iso3: 'NZL', dialCode: '+64', currencyCode: 'NZD', currencyName: 'New Zealand Dollar', currencySymbol: 'NZ$', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Auckland' },
  { name: 'Israel', nameAr: 'إسرائيل', iso2: 'IL', iso3: 'ISR', dialCode: '+972', currencyCode: 'ILS', currencyName: 'Israeli Shekel', currencySymbol: '₪', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Jerusalem' },
  { name: 'Czech Republic', nameAr: 'التشيك', iso2: 'CZ', iso3: 'CZE', dialCode: '+420', currencyCode: 'CZK', currencyName: 'Czech Koruna', currencySymbol: 'Kč', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Prague' },
  { name: 'Hungary', nameAr: 'المجر', iso2: 'HU', iso3: 'HUN', dialCode: '+36', currencyCode: 'HUF', currencyName: 'Hungarian Forint', currencySymbol: 'Ft', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Budapest' },
  { name: 'Romania', nameAr: 'رومانيا', iso2: 'RO', iso3: 'ROU', dialCode: '+40', currencyCode: 'RON', currencyName: 'Romanian Leu', currencySymbol: 'lei', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Bucharest' },
  { name: 'Ukraine', nameAr: 'أوكرانيا', iso2: 'UA', iso3: 'UKR', dialCode: '+380', currencyCode: 'UAH', currencyName: 'Ukrainian Hryvnia', currencySymbol: '₴', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Kyiv' },
  { name: 'Belarus', nameAr: 'بيلاروسيا', iso2: 'BY', iso3: 'BLR', dialCode: '+375', currencyCode: 'BYN', currencyName: 'Belarusian Ruble', currencySymbol: 'Br', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Minsk' },
  { name: 'Bulgaria', nameAr: 'بلغاريا', iso2: 'BG', iso3: 'BGR', dialCode: '+359', currencyCode: 'BGN', currencyName: 'Bulgarian Lev', currencySymbol: 'лв', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Sofia' },
  { name: 'Croatia', nameAr: 'كرواتيا', iso2: 'HR', iso3: 'HRV', dialCode: '+385', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Zagreb' },
  { name: 'Serbia', nameAr: 'صربيا', iso2: 'RS', iso3: 'SRB', dialCode: '+381', currencyCode: 'RSD', currencyName: 'Serbian Dinar', currencySymbol: 'дин', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Belgrade' },
  { name: 'Slovakia', nameAr: 'سلوفاكيا', iso2: 'SK', iso3: 'SVK', dialCode: '+421', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Bratislava' },
  { name: 'Slovenia', nameAr: 'سلوفينيا', iso2: 'SI', iso3: 'SVN', dialCode: '+386', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Ljubljana' },
  { name: 'Lithuania', nameAr: 'ليتوانيا', iso2: 'LT', iso3: 'LTU', dialCode: '+370', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Vilnius' },
  { name: 'Latvia', nameAr: 'لاتفيا', iso2: 'LV', iso3: 'LVA', dialCode: '+371', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Riga' },
  { name: 'Estonia', nameAr: 'إستونيا', iso2: 'EE', iso3: 'EST', dialCode: '+372', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Tallinn' },
  { name: 'Iceland', nameAr: 'آيسلندا', iso2: 'IS', iso3: 'ISL', dialCode: '+354', currencyCode: 'ISK', currencyName: 'Icelandic Krona', currencySymbol: 'kr', defaultLanguage: 'en', region: 'Europe', timezone: 'Atlantic/Reykjavik' },
  { name: 'Luxembourg', nameAr: 'لوكسمبورغ', iso2: 'LU', iso3: 'LUX', dialCode: '+352', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Luxembourg' },
  { name: 'Malta', nameAr: 'مالطا', iso2: 'MT', iso3: 'MLT', dialCode: '+356', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Malta' },
  { name: 'Cyprus', nameAr: 'قبرص', iso2: 'CY', iso3: 'CYP', dialCode: '+357', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Nicosia' },
  { name: 'Albania', nameAr: 'ألبانيا', iso2: 'AL', iso3: 'ALB', dialCode: '+355', currencyCode: 'ALL', currencyName: 'Albanian Lek', currencySymbol: 'L', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Tirane' },
  { name: 'Bosnia and Herzegovina', nameAr: 'البوسنة والهرسك', iso2: 'BA', iso3: 'BIH', dialCode: '+387', currencyCode: 'BAM', currencyName: 'Bosnian Mark', currencySymbol: 'KM', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Sarajevo' },
  { name: 'Moldova', nameAr: 'مولدوفا', iso2: 'MD', iso3: 'MDA', dialCode: '+373', currencyCode: 'MDL', currencyName: 'Moldovan Leu', currencySymbol: 'L', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Chisinau' },
  { name: 'Montenegro', nameAr: 'الجبل الأسود', iso2: 'ME', iso3: 'MNE', dialCode: '+382', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Podgorica' },
  { name: 'North Macedonia', nameAr: 'شمال مقدونيا', iso2: 'MK', iso3: 'MKD', dialCode: '+389', currencyCode: 'MKD', currencyName: 'Macedonian Denar', currencySymbol: 'ден', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Skopje' },
  { name: 'Kosovo', nameAr: 'كوسوفو', iso2: 'XK', iso3: 'XKX', dialCode: '+383', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Belgrade' },
  { name: 'Andorra', nameAr: 'أندورا', iso2: 'AD', iso3: 'AND', dialCode: '+376', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Andorra' },
  { name: 'Monaco', nameAr: 'موناكو', iso2: 'MC', iso3: 'MCO', dialCode: '+377', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Monaco' },
  { name: 'San Marino', nameAr: 'سان مارينو', iso2: 'SM', iso3: 'SMR', dialCode: '+378', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/San_Marino' },
  { name: 'Vatican City', nameAr: 'الفاتيكان', iso2: 'VA', iso3: 'VAT', dialCode: '+379', currencyCode: 'EUR', currencyName: 'Euro', currencySymbol: '€', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Vatican' },
  { name: 'Liechtenstein', nameAr: 'ليختنشتاين', iso2: 'LI', iso3: 'LIE', dialCode: '+423', currencyCode: 'CHF', currencyName: 'Swiss Franc', currencySymbol: 'CHF', defaultLanguage: 'en', region: 'Europe', timezone: 'Europe/Vaduz' },
  { name: 'Afghanistan', nameAr: 'أفغانستان', iso2: 'AF', iso3: 'AFG', dialCode: '+93', currencyCode: 'AFN', currencyName: 'Afghan Afghani', currencySymbol: '؋', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Kabul' },
  { name: 'Armenia', nameAr: 'أرمينيا', iso2: 'AM', iso3: 'ARM', dialCode: '+374', currencyCode: 'AMD', currencyName: 'Armenian Dram', currencySymbol: '֏', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Yerevan' },
  { name: 'Azerbaijan', nameAr: 'أذربيجان', iso2: 'AZ', iso3: 'AZE', dialCode: '+994', currencyCode: 'AZN', currencyName: 'Azerbaijani Manat', currencySymbol: '₼', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Baku' },
  { name: 'Bhutan', nameAr: 'بوتان', iso2: 'BT', iso3: 'BTN', dialCode: '+975', currencyCode: 'BTN', currencyName: 'Bhutanese Ngultrum', currencySymbol: 'Nu', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Thimphu' },
  { name: 'Brunei', nameAr: 'بروناي', iso2: 'BN', iso3: 'BRN', dialCode: '+673', currencyCode: 'BND', currencyName: 'Brunei Dollar', currencySymbol: 'B$', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Brunei' },
  { name: 'Cambodia', nameAr: 'كمبوديا', iso2: 'KH', iso3: 'KHM', dialCode: '+855', currencyCode: 'KHR', currencyName: 'Cambodian Riel', currencySymbol: '៛', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Phnom_Penh' },
  { name: 'Georgia', nameAr: 'جورجيا', iso2: 'GE', iso3: 'GEO', dialCode: '+995', currencyCode: 'GEL', currencyName: 'Georgian Lari', currencySymbol: '₾', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Tbilisi' },
  { name: 'Kazakhstan', nameAr: 'كازاخستان', iso2: 'KZ', iso3: 'KAZ', dialCode: '+7', currencyCode: 'KZT', currencyName: 'Kazakhstani Tenge', currencySymbol: '₸', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Almaty' },
  { name: 'Kyrgyzstan', nameAr: 'قيرغيزستان', iso2: 'KG', iso3: 'KGZ', dialCode: '+996', currencyCode: 'KGS', currencyName: 'Kyrgyzstani Som', currencySymbol: 'с', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Bishkek' },
  { name: 'Laos', nameAr: 'لاوس', iso2: 'LA', iso3: 'LAO', dialCode: '+856', currencyCode: 'LAK', currencyName: 'Lao Kip', currencySymbol: '₭', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Vientiane' },
  { name: 'Maldives', nameAr: 'جزر المالديف', iso2: 'MV', iso3: 'MDV', dialCode: '+960', currencyCode: 'MVR', currencyName: 'Maldivian Rufiyaa', currencySymbol: 'Rf', defaultLanguage: 'en', region: 'Asia', timezone: 'Indian/Maldives' },
  { name: 'Mongolia', nameAr: 'منغوليا', iso2: 'MN', iso3: 'MNG', dialCode: '+976', currencyCode: 'MNT', currencyName: 'Mongolian Tugrik', currencySymbol: '₮', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Ulaanbaatar' },
  { name: 'Myanmar', nameAr: 'ميانمار', iso2: 'MM', iso3: 'MMR', dialCode: '+95', currencyCode: 'MMK', currencyName: 'Myanmar Kyat', currencySymbol: 'K', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Yangon' },
  { name: 'Nepal', nameAr: 'نيبال', iso2: 'NP', iso3: 'NPL', dialCode: '+977', currencyCode: 'NPR', currencyName: 'Nepalese Rupee', currencySymbol: 'Rs', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Kathmandu' },
  { name: 'North Korea', nameAr: 'كوريا الشمالية', iso2: 'KP', iso3: 'PRK', dialCode: '+850', currencyCode: 'KPW', currencyName: 'North Korean Won', currencySymbol: '₩', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Pyongyang' },
  { name: 'Sri Lanka', nameAr: 'سريلانكا', iso2: 'LK', iso3: 'LKA', dialCode: '+94', currencyCode: 'LKR', currencyName: 'Sri Lankan Rupee', currencySymbol: 'Rs', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Colombo' },
  { name: 'Taiwan', nameAr: 'تايوان', iso2: 'TW', iso3: 'TWN', dialCode: '+886', currencyCode: 'TWD', currencyName: 'Taiwan Dollar', currencySymbol: 'NT$', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Taipei' },
  { name: 'Tajikistan', nameAr: 'طاجيكستان', iso2: 'TJ', iso3: 'TJK', dialCode: '+992', currencyCode: 'TJS', currencyName: 'Tajikistani Somoni', currencySymbol: 'SM', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Dushanbe' },
  { name: 'Timor-Leste', nameAr: 'تيمور الشرقية', iso2: 'TL', iso3: 'TLS', dialCode: '+670', currencyCode: 'USD', currencyName: 'US Dollar', currencySymbol: '$', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Dili' },
  { name: 'Turkmenistan', nameAr: 'تركمانستان', iso2: 'TM', iso3: 'TKM', dialCode: '+993', currencyCode: 'TMT', currencyName: 'Turkmenistani Manat', currencySymbol: 'm', defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Ashgabat' },
  { name: 'Uzbekistan', nameAr: 'أوزبكستان', iso2: 'UZ', iso3: 'UZB', dialCode: '+998', currencyCode: 'UZS', currencyName: 'Uzbekistani Som', currencySymbol: "so'm", defaultLanguage: 'en', region: 'Asia', timezone: 'Asia/Tashkent' },
  { name: 'Angola', nameAr: 'أنغولا', iso2: 'AO', iso3: 'AGO', dialCode: '+244', currencyCode: 'AOA', currencyName: 'Angolan Kwanza', currencySymbol: 'Kz', defaultLanguage: 'pt', region: 'Africa', timezone: 'Africa/Luanda' },
  { name: 'Benin', nameAr: 'بنين', iso2: 'BJ', iso3: 'BEN', dialCode: '+229', currencyCode: 'XOF', currencyName: 'West African CFA Franc', currencySymbol: 'CFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Porto-Novo' },
  { name: 'Botswana', nameAr: 'بوتسوانا', iso2: 'BW', iso3: 'BWA', dialCode: '+267', currencyCode: 'BWP', currencyName: 'Botswana Pula', currencySymbol: 'P', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Gaborone' },
  { name: 'Burkina Faso', nameAr: 'بوركينا فاسو', iso2: 'BF', iso3: 'BFA', dialCode: '+226', currencyCode: 'XOF', currencyName: 'West African CFA Franc', currencySymbol: 'CFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Ouagadougou' },
  { name: 'Burundi', nameAr: 'بوروندي', iso2: 'BI', iso3: 'BDI', dialCode: '+257', currencyCode: 'BIF', currencyName: 'Burundian Franc', currencySymbol: 'FBu', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Bujumbura' },
  { name: 'Cabo Verde', nameAr: 'كابو فيردي', iso2: 'CV', iso3: 'CPV', dialCode: '+238', currencyCode: 'CVE', currencyName: 'Cape Verdean Escudo', currencySymbol: '$', defaultLanguage: 'pt', region: 'Africa', timezone: 'Atlantic/Cape_Verde' },
  { name: 'Cameroon', nameAr: 'الكاميرون', iso2: 'CM', iso3: 'CMR', dialCode: '+237', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', currencySymbol: 'FCFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Douala' },
  { name: 'Central African Republic', nameAr: 'أفريقيا الوسطى', iso2: 'CF', iso3: 'CAF', dialCode: '+236', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', currencySymbol: 'FCFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Bangui' },
  { name: 'Chad', nameAr: 'تشاد', iso2: 'TD', iso3: 'TCD', dialCode: '+235', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', currencySymbol: 'FCFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Ndjamena' },
  { name: 'Congo (Brazzaville)', nameAr: 'الكونغو', iso2: 'CG', iso3: 'COG', dialCode: '+242', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', currencySymbol: 'FCFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Brazzaville' },
  { name: 'Congo (Kinshasa)', nameAr: 'الكونغو الديمقراطية', iso2: 'CD', iso3: 'COD', dialCode: '+243', currencyCode: 'CDF', currencyName: 'Congolese Franc', currencySymbol: 'FC', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Kinshasa' },
  { name: "Cote d'Ivoire", nameAr: 'ساحل العاج', iso2: 'CI', iso3: 'CIV', dialCode: '+225', currencyCode: 'XOF', currencyName: 'West African CFA Franc', currencySymbol: 'CFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Abidjan' },
  { name: 'Eritrea', nameAr: 'إريتريا', iso2: 'ER', iso3: 'ERI', dialCode: '+291', currencyCode: 'ERN', currencyName: 'Eritrean Nakfa', currencySymbol: 'Nfk', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Asmara' },
  { name: 'Eswatini', nameAr: 'إسواتيني', iso2: 'SZ', iso3: 'SWZ', dialCode: '+268', currencyCode: 'SZL', currencyName: 'Swazi Lilangeni', currencySymbol: 'E', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Mbabane' },
  { name: 'Gabon', nameAr: 'الغابون', iso2: 'GA', iso3: 'GAB', dialCode: '+241', currencyCode: 'XAF', currencyName: 'Central African CFA Franc', currencySymbol: 'FCFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Libreville' },
  { name: 'Gambia', nameAr: 'غامبيا', iso2: 'GM', iso3: 'GMB', dialCode: '+220', currencyCode: 'GMD', currencyName: 'Gambian Dalasi', currencySymbol: 'D', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Banjul' },
  { name: 'Guinea', nameAr: 'غينيا', iso2: 'GN', iso3: 'GIN', dialCode: '+224', currencyCode: 'GNF', currencyName: 'Guinean Franc', currencySymbol: 'FG', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Conakry' },
  { name: 'Guinea-Bissau', nameAr: 'غينيا بيساو', iso2: 'GW', iso3: 'GNB', dialCode: '+245', currencyCode: 'XOF', currencyName: 'West African CFA Franc', currencySymbol: 'CFA', defaultLanguage: 'pt', region: 'Africa', timezone: 'Africa/Bissau' },
  { name: 'Lesotho', nameAr: 'ليسوتو', iso2: 'LS', iso3: 'LSO', dialCode: '+266', currencyCode: 'LSL', currencyName: 'Lesotho Loti', currencySymbol: 'L', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Maseru' },
  { name: 'Liberia', nameAr: 'ليبيريا', iso2: 'LR', iso3: 'LBR', dialCode: '+231', currencyCode: 'LRD', currencyName: 'Liberian Dollar', currencySymbol: 'L$', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Monrovia' },
  { name: 'Madagascar', nameAr: 'مدغشقر', iso2: 'MG', iso3: 'MDG', dialCode: '+261', currencyCode: 'MGA', currencyName: 'Malagasy Ariary', currencySymbol: 'Ar', defaultLanguage: 'fr', region: 'Africa', timezone: 'Indian/Antananarivo' },
  { name: 'Malawi', nameAr: 'مالاوي', iso2: 'MW', iso3: 'MWI', dialCode: '+265', currencyCode: 'MWK', currencyName: 'Malawian Kwacha', currencySymbol: 'MK', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Blantyre' },
  { name: 'Mali', nameAr: 'مالي', iso2: 'ML', iso3: 'MLI', dialCode: '+223', currencyCode: 'XOF', currencyName: 'West African CFA Franc', currencySymbol: 'CFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Bamako' },
  { name: 'Mauritius', nameAr: 'موريشيوس', iso2: 'MU', iso3: 'MUS', dialCode: '+230', currencyCode: 'MUR', currencyName: 'Mauritian Rupee', currencySymbol: 'Rs', defaultLanguage: 'en', region: 'Africa', timezone: 'Indian/Mauritius' },
  { name: 'Mozambique', nameAr: 'موزمبيق', iso2: 'MZ', iso3: 'MOZ', dialCode: '+258', currencyCode: 'MZN', currencyName: 'Mozambican Metical', currencySymbol: 'MT', defaultLanguage: 'pt', region: 'Africa', timezone: 'Africa/Maputo' },
  { name: 'Namibia', nameAr: 'ناميبيا', iso2: 'NA', iso3: 'NAM', dialCode: '+264', currencyCode: 'NAD', currencyName: 'Namibian Dollar', currencySymbol: 'N$', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Windhoek' },
  { name: 'Niger', nameAr: 'النيجر', iso2: 'NE', iso3: 'NER', dialCode: '+227', currencyCode: 'XOF', currencyName: 'West African CFA Franc', currencySymbol: 'CFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Niamey' },
  { name: 'Rwanda', nameAr: 'رواندا', iso2: 'RW', iso3: 'RWA', dialCode: '+250', currencyCode: 'RWF', currencyName: 'Rwandan Franc', currencySymbol: 'RF', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Kigali' },
  { name: 'Sao Tome and Principe', nameAr: 'ساو تومي', iso2: 'ST', iso3: 'STP', dialCode: '+239', currencyCode: 'STN', currencyName: 'Sao Tome Dobra', currencySymbol: 'Db', defaultLanguage: 'pt', region: 'Africa', timezone: 'Africa/Sao_Tome' },
  { name: 'Senegal', nameAr: 'السنغال', iso2: 'SN', iso3: 'SEN', dialCode: '+221', currencyCode: 'XOF', currencyName: 'West African CFA Franc', currencySymbol: 'CFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Dakar' },
  { name: 'Seychelles', nameAr: 'سيشل', iso2: 'SC', iso3: 'SYC', dialCode: '+248', currencyCode: 'SCR', currencyName: 'Seychellois Rupee', currencySymbol: 'SR', defaultLanguage: 'en', region: 'Africa', timezone: 'Indian/Mahe' },
  { name: 'Sierra Leone', nameAr: 'سيراليون', iso2: 'SL', iso3: 'SLE', dialCode: '+232', currencyCode: 'SLL', currencyName: 'Sierra Leonean Leone', currencySymbol: 'Le', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Freetown' },
  { name: 'Togo', nameAr: 'توغو', iso2: 'TG', iso3: 'TGO', dialCode: '+228', currencyCode: 'XOF', currencyName: 'West African CFA Franc', currencySymbol: 'CFA', defaultLanguage: 'fr', region: 'Africa', timezone: 'Africa/Lome' },
  { name: 'Zambia', nameAr: 'زامبيا', iso2: 'ZM', iso3: 'ZMB', dialCode: '+260', currencyCode: 'ZMW', currencyName: 'Zambian Kwacha', currencySymbol: 'K', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Lusaka' },
  { name: 'Zimbabwe', nameAr: 'زيمبابوي', iso2: 'ZW', iso3: 'ZWE', dialCode: '+263', currencyCode: 'ZWL', currencyName: 'Zimbabwean Dollar', currencySymbol: 'Z$', defaultLanguage: 'en', region: 'Africa', timezone: 'Africa/Harare' },
  { name: 'Belize', nameAr: 'بليز', iso2: 'BZ', iso3: 'BLZ', dialCode: '+501', currencyCode: 'BZD', currencyName: 'Belize Dollar', currencySymbol: 'BZ$', defaultLanguage: 'en', region: 'Americas', timezone: 'America/Belize' },
  { name: 'Bolivia', nameAr: 'بوليفيا', iso2: 'BO', iso3: 'BOL', dialCode: '+591', currencyCode: 'BOB', currencyName: 'Bolivian Boliviano', currencySymbol: 'Bs', defaultLanguage: 'es', region: 'Americas', timezone: 'America/La_Paz' },
  { name: 'Costa Rica', nameAr: 'كوستاريكا', iso2: 'CR', iso3: 'CRI', dialCode: '+506', currencyCode: 'CRC', currencyName: 'Costa Rican Colon', currencySymbol: '₡', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Costa_Rica' },
  { name: 'Cuba', nameAr: 'كوبا', iso2: 'CU', iso3: 'CUB', dialCode: '+53', currencyCode: 'CUP', currencyName: 'Cuban Peso', currencySymbol: '$', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Havana' },
  { name: 'Dominican Republic', nameAr: 'الدومينيكان', iso2: 'DO', iso3: 'DOM', dialCode: '+1', currencyCode: 'DOP', currencyName: 'Dominican Peso', currencySymbol: 'RD$', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Santo_Domingo' },
  { name: 'Ecuador', nameAr: 'الإكوادور', iso2: 'EC', iso3: 'ECU', dialCode: '+593', currencyCode: 'USD', currencyName: 'US Dollar', currencySymbol: '$', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Guayaquil' },
  { name: 'El Salvador', nameAr: 'السلفادور', iso2: 'SV', iso3: 'SLV', dialCode: '+503', currencyCode: 'USD', currencyName: 'US Dollar', currencySymbol: '$', defaultLanguage: 'es', region: 'Americas', timezone: 'America/El_Salvador' },
  { name: 'Guatemala', nameAr: 'غواتيمالا', iso2: 'GT', iso3: 'GTM', dialCode: '+502', currencyCode: 'GTQ', currencyName: 'Guatemalan Quetzal', currencySymbol: 'Q', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Guatemala' },
  { name: 'Guyana', nameAr: 'غيانا', iso2: 'GY', iso3: 'GUY', dialCode: '+592', currencyCode: 'GYD', currencyName: 'Guyanese Dollar', currencySymbol: 'G$', defaultLanguage: 'en', region: 'Americas', timezone: 'America/Guyana' },
  { name: 'Haiti', nameAr: 'هايتي', iso2: 'HT', iso3: 'HTI', dialCode: '+509', currencyCode: 'HTG', currencyName: 'Haitian Gourde', currencySymbol: 'G', defaultLanguage: 'fr', region: 'Americas', timezone: 'America/Port-au-Prince' },
  { name: 'Honduras', nameAr: 'هندوراس', iso2: 'HN', iso3: 'HND', dialCode: '+504', currencyCode: 'HNL', currencyName: 'Honduran Lempira', currencySymbol: 'L', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Tegucigalpa' },
  { name: 'Jamaica', nameAr: 'جامايكا', iso2: 'JM', iso3: 'JAM', dialCode: '+1', currencyCode: 'JMD', currencyName: 'Jamaican Dollar', currencySymbol: 'J$', defaultLanguage: 'en', region: 'Americas', timezone: 'America/Jamaica' },
  { name: 'Nicaragua', nameAr: 'نيكاراغوا', iso2: 'NI', iso3: 'NIC', dialCode: '+505', currencyCode: 'NIO', currencyName: 'Nicaraguan Cordoba', currencySymbol: 'C$', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Managua' },
  { name: 'Panama', nameAr: 'بنما', iso2: 'PA', iso3: 'PAN', dialCode: '+507', currencyCode: 'USD', currencyName: 'US Dollar', currencySymbol: '$', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Panama' },
  { name: 'Paraguay', nameAr: 'باراغواي', iso2: 'PY', iso3: 'PRY', dialCode: '+595', currencyCode: 'PYG', currencyName: 'Paraguayan Guarani', currencySymbol: '₲', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Asuncion' },
  { name: 'Suriname', nameAr: 'سورينام', iso2: 'SR', iso3: 'SUR', dialCode: '+597', currencyCode: 'SRD', currencyName: 'Surinamese Dollar', currencySymbol: 'Sr$', defaultLanguage: 'en', region: 'Americas', timezone: 'America/Paramaribo' },
  { name: 'Uruguay', nameAr: 'الأوروغواي', iso2: 'UY', iso3: 'URY', dialCode: '+598', currencyCode: 'UYU', currencyName: 'Uruguayan Peso', currencySymbol: 'U$', defaultLanguage: 'es', region: 'Americas', timezone: 'America/Montevideo' },
  { name: 'Fiji', nameAr: 'فيجي', iso2: 'FJ', iso3: 'FJI', dialCode: '+679', currencyCode: 'FJD', currencyName: 'Fijian Dollar', currencySymbol: 'FJ$', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Fiji' },
  { name: 'Kiribati', nameAr: 'كيريباتي', iso2: 'KI', iso3: 'KIR', dialCode: '+686', currencyCode: 'AUD', currencyName: 'Australian Dollar', currencySymbol: 'A$', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Tarawa' },
  { name: 'Marshall Islands', nameAr: 'جزر مارشال', iso2: 'MH', iso3: 'MHL', dialCode: '+692', currencyCode: 'USD', currencyName: 'US Dollar', currencySymbol: '$', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Majuro' },
  { name: 'Micronesia', nameAr: 'ميكرونيزيا', iso2: 'FM', iso3: 'FSM', dialCode: '+691', currencyCode: 'USD', currencyName: 'US Dollar', currencySymbol: '$', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Pohnpei' },
  { name: 'Nauru', nameAr: 'ناورو', iso2: 'NR', iso3: 'NRU', dialCode: '+674', currencyCode: 'AUD', currencyName: 'Australian Dollar', currencySymbol: 'A$', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Nauru' },
  { name: 'Palau', nameAr: 'بالاو', iso2: 'PW', iso3: 'PLW', dialCode: '+680', currencyCode: 'USD', currencyName: 'US Dollar', currencySymbol: '$', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Palau' },
  { name: 'Papua New Guinea', nameAr: 'بابوا غينيا الجديدة', iso2: 'PG', iso3: 'PNG', dialCode: '+675', currencyCode: 'PGK', currencyName: 'Papua New Guinean Kina', currencySymbol: 'K', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Port_Moresby' },
  { name: 'Samoa', nameAr: 'ساموا', iso2: 'WS', iso3: 'WSM', dialCode: '+685', currencyCode: 'WST', currencyName: 'Samoan Tala', currencySymbol: 'T', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Apia' },
  { name: 'Solomon Islands', nameAr: 'جزر سليمان', iso2: 'SB', iso3: 'SLB', dialCode: '+677', currencyCode: 'SBD', currencyName: 'Solomon Islands Dollar', currencySymbol: 'SI$', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Guadalcanal' },
  { name: 'Tonga', nameAr: 'تونغا', iso2: 'TO', iso3: 'TON', dialCode: '+676', currencyCode: 'TOP', currencyName: 'Tongan Paanga', currencySymbol: 'T$', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Tongatapu' },
  { name: 'Tuvalu', nameAr: 'توفالو', iso2: 'TV', iso3: 'TUV', dialCode: '+688', currencyCode: 'AUD', currencyName: 'Australian Dollar', currencySymbol: 'A$', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Funafuti' },
  { name: 'Vanuatu', nameAr: 'فانواتو', iso2: 'VU', iso3: 'VUT', dialCode: '+678', currencyCode: 'VUV', currencyName: 'Vanuatu Vatu', currencySymbol: 'Vt', defaultLanguage: 'en', region: 'Oceania', timezone: 'Pacific/Efate' },
];

async function main() {
  console.log('Seeding countries...');
  for (const c of COUNTRIES) {
    await prisma.country.upsert({
      where: { name: c.name },
      create: c,
      update: c,
    });
  }
  console.log(`Seeded ${COUNTRIES.length} countries`);

  // Seed currencies from country data
  console.log('Seeding currencies...');
  const seenCurrencies = new Set<string>();
  const countries = await prisma.country.findMany();
  for (const country of countries) {
    if (seenCurrencies.has(country.currencyCode)) continue;
    seenCurrencies.add(country.currencyCode);
    await prisma.currency.upsert({
      where: { code: country.currencyCode },
      create: {
        code: country.currencyCode,
        name: country.currencyName,
        symbol: country.currencySymbol,
        countryId: country.id,
      },
      update: {
        name: country.currencyName,
        symbol: country.currencySymbol,
        countryId: country.id,
      },
    });
  }
  console.log(`Seeded ${seenCurrencies.size} currencies`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
